### ISSUE TITLE
Cannot find the declaration of element 'changelog'.

### ISSUE THREAD

**Issue by kadkaz** [liquigraph/liquigraph#79]
I got validation exception and could not find in your current version good changelog.xml with xsd.

and I got your example from the site:

```
<changelog>
    <changeset id="hello-world" author="you">
        <query>CREATE (n:Sentence {text:'Hello monde!'}) RETURN n</query>
    </changeset>
    <changeset id="hello-world-fixed" author="you">
        <query>MATCH (n:Sentence {text:'Hello monde!'}) SET n.text='Hello world!' RETURN n</query>
    </changeset>
</changelog>

```

```
Caused by: java.lang.IllegalArgumentException: 
    cvc-elt.1: Cannot find the declaration of element 'changelog'.
    at org.liquigraph.core.io.xml.ChangelogParser.parseChangelog(ChangelogParser.java:64) ~[liquigraph-core-1.0-RC3.jar:na]
    at org.liquigraph.core.io.xml.ChangelogParser.parse(ChangelogParser.java:56) ~[liquigraph-core-1.0-RC3.jar:na]
    at org.liquigraph.core.api.MigrationRunner.parseChangesets(MigrationRunner.java:84) ~[liquigraph-core-1.0-RC3.jar:na]
    at org.liquigraph.core.api.MigrationRunner.runMigrations(MigrationRunner.java:66) ~[liquigraph-core-1.0-RC3.jar:na]
    at org.liquigraph.core.api.Liquigraph.runMigrations(Liquigraph.java:63) ~[liquigraph-core-1.0-RC3.jar:na]
```

**Comment by fbiville** [comment]
Hi, thanks for reporting this!

There was a bug (#71) in RC3 when you declared a changelog with the XML schema reference. It is now fixed but not released yet.

In the meantime, you can either:

 - build Liquigraph from sources
 - grab the latest SNAPSHOT [version](https://oss.sonatype.org/content/repositories/snapshots/org/liquigraph/)
 - do not reference any schema when running with Liquigraph RC3

Does that help?

**Comment by fbiville** [comment]
Can you confirm any of the above workarounds solve your issue? Thanks! :)

**Comment by fbiville** [comment]
Feel free to reopen this issue if the bug still occurs in the latest versions (see how to proceed above).

**Comment by sujitreddyg** [comment]
Hi, I tried with version 3.0.1, looks like this issue is not fixed yet. Here is the log:

	cvc-elt.1.a: Cannot find the declaration of element 'changelog'.
	at org.liquigraph.core.io.xml.ChangelogParser.parseChangelog(ChangelogParser.java:65) ~[liquigraph-core-3.0.1.jar:na]
	at org.liquigraph.core.io.xml.ChangelogParser.parse(ChangelogParser.java:57) ~[liquigraph-core-3.0.1.jar:na]
	at org.liquigraph.core.api.MigrationRunner.parseChangesets(MigrationRunner.java:86) ~[liquigraph-core-3.0.1.jar:na]
	at org.liquigraph.core.api.MigrationRunner.runMigrations(MigrationRunner.java:67) ~[liquigraph-core-3.0.1.jar:na]
	at org.liquigraph.core.api.Liquigraph.runMigrations(Liquigraph.java:63) ~[liquigraph-core-3.0.1.jar:na]

**Comment by fbiville** [comment]
@sujitreddyg if you replace:
```
<changelog>
```
with
```
<?xml version="1.0" encoding="UTF-8"?>
<changelog xmlns="https://fbiville.github.io/liquigraph/schema/1.0/liquigraph.xsd">`
````
What happens?

**Comment by sujitreddyg** [comment]
@fbiville Thanks! I tried with and without xmlns, in both cases we are getting same error. Validation with both ImplicitSchemaValidator and ExplicitSchemaValidator are resulting in same errors. Please let me know if you have any suggestions.

Thanks!

**Comment by fbiville** [comment]
How are you using Liquigraph? 
Are you using the shell script, the Maven plugin or the core classes directly?
Also, do you have direct access to https://fbiville.github.io/liquigraph/schema/1.0/liquigraph.xsd in your environment?

**Comment by sujitreddyg** [comment]
We are using Liquigraph in Spring Boot web application version 1.4.2.RELEASE - https://projects.spring.io/spring-boot/. 
Added to project dependencies using Maven:
```
<dependency>
   <groupId>org.liquigraph</groupId>
   <artifactId>liquigraph-core</artifactId>
   <version>3.0.1</version>
 </dependency>
```

Yes, the system has access to that xsd.

Thanks!

**Comment by fbiville** [comment]
Not that it is linked to the issue you're having, but I'm afraid that Spring Boot support is not ready yet. We're working on a fix (@mvitz actually is).

Still, I'm not sure what's going on with this.
Could you maybe provide a minimalistic way to reproduce the issue? Thanks in advance!

**Comment by mvitz** [comment]
You should at least show how you are using liquigraph inside your spring-boot application.

**Comment by sujitreddyg** [comment]
Hi, 
Sorry for the confusion. Our usage of Liquigraph has nothing to do with Springboot, it’s just our Application runs on Springboot. In @PostConstruct method of Configuration file, we are using this piece of code to start Liquigraph migration:
```
      org.liquigraph.core.configuration.Configuration configuration = new ConfigurationBuilder()
              .withMasterChangelogLocation("liquigraph/changelog.xml")
              .withUri(”jdbc:neo4j:<uri>")
              .withRunMode()
              .withUsername(”user_name")
              .withPassword(”password")
              .build();

      Liquigraph liquigraph = new Liquigraph();
      liquigraph.runMigrations(configuration);
```

Thanks!

**Comment by fbiville** [comment]
@sujitreddyg I'm afraid this still has to do with the way Spring Boot packages JAR.
Luckily enough, the full-fledged support for Spring Boot has recently landed in Liquigraph 3.x (documentation to be added soon).

If you wanna give it a try before the release, please replace your Liquigraph dependency with something like the following (if you use something else than Maven, it should be pretty similar anyway)

```xml
<dependency>
   <groupId>org.liquigraph</groupId>
   <artifactId>liquigraph-spring-boot-starter</artifactId>
   <version>3.0.2-SNAPSHOT</version>
</dependency>
```

And do not forget to add the SNAPSHOT repository:

```xml
     <repositories>
       <repository>
         <id>snapshots-repo</id>
         <url>https://oss.sonatype.org/content/repositories/snapshots</url>
         <releases><enabled>false</enabled></releases>
         <snapshots><enabled>true</enabled></snapshots>
       </repository>
     </repositories>
```

Then, you can follow the example of https://github.com/fbiville/liquigraph-spring-boot-example. 

Please note that there even is a simpler way: you can simply add `@EnableAutoConfiguration` and properties `liquigraph.user`, `liquigraph.password` and `liquigraph.url` (JDBC URL) to your `application.properties` and it should just work!

**Comment by mvitz** [comment]
Your description exactly shows the code I'm using in our last neo4j based project. And this normally works.

Does your project consist of several JARs? Maybe the configuration file is in another module than the code that loads the configuration file.

**Comment by sujitreddyg** [comment]
@fbiville Thanks! We will try liquigraph-spring-boot-starter. Sorry for delayed response.

@mvitz We are using spring-boot-maven-plugin to build a single jar. Do you think this might be causing the problem?

**Comment by fbiville** [comment]
@sujitreddyg have you had a change to test the new Spring Boot starter module? This is now nicely documented: http://fbiville.github.io/liquigraph/latest/index.html#spring-boot.

**Comment by fbiville** [comment]
Feel free to comment again if you are still facing issues.

**Comment by sey** [comment]
Hi there, 

I'm facing the exact same issue. Tried with 3.0.4-SNAPSHOT and 3.1.0 on a Spring Boot project.
Tried with explicit and implicit schema validation. 
Tried on a separate Java project with just LiquiGraph as a dependency. 
Nothing works.

I tried on a different computer outside of the network where it is not working and it works, no problems.

I think the validation process as a strong dependency on the **Internet** access. Even with implicit validation it still goes to the Internet to get the XML Schema definition itself and other stuff.

It would be great to add a property to enable/disable the validation process.

What do you think?

**Comment by fbiville** [comment]
@sey work has started and is tracked by this [issue](https://github.com/liquigraph/liquigraph/issues/241).
